"""drop unused notes outbox and chunk tables

Revision ID: 12c471ee5813
Revises: a3e3b83fb67c
Create Date: 2026-08-18 22:17:55.509090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "12c471ee5813"
down_revision: str | None = "a3e3b83fb67c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transcript_chunks")
    op.drop_table("meeting_notes")
    op.drop_index(op.f("ix_outbox_owner_received"), table_name="outbox_entries")
    op.drop_table("outbox_entries")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_entries",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("client_entry_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("owner_user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("owner_tenant_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("aggregate_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("aggregate_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("operation", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "client_updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "server_received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "applied_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("outbox_entries_pkey")),
        sa.UniqueConstraint(
            "owner_user_id",
            "client_entry_id",
            name=op.f("uq_outbox_owner_client_entry"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_outbox_owner_received"),
        "outbox_entries",
        ["owner_tenant_id", "owner_user_id", "server_received_at"],
        unique=False,
    )
    op.create_table(
        "meeting_notes",
        sa.Column("meeting_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("notes_markdown", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "notes_json",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("meeting_notes_meeting_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meeting_id", name=op.f("meeting_notes_pkey")),
    )
    op.create_table(
        "transcript_chunks",
        sa.Column("meeting_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("meeting_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("transcript_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("model_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("chunk_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("overlap", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("transcript_chunks_meeting_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meeting_id", name=op.f("transcript_chunks_pkey")),
    )
    # ### end Alembic commands ###
