"""separate english cache from the summary document

Revision ID: 30d536110d88
Revises: 12c471ee5813
Create Date: 2026-08-18 22:36:23.952925

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "30d536110d88"
down_revision: str | None = "12c471ee5813"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "summary_processes",
        sa.Column("english_cache", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summary_processes", "english_cache")
    # ### end Alembic commands ###
