"""initial schema

Revision ID: 384fafdd3db8
Revises:
Create Date: 2026-08-18 11:10:01.894524

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "384fafdd3db8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("owner_tenant_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("folder_path", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_meetings_owner", "meetings", ["owner_tenant_id", "owner_user_id"], unique=False
    )
    op.create_table(
        "outbox_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_entry_id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("owner_tenant_id", sa.String(), nullable=False),
        sa.Column("aggregate_type", sa.String(), nullable=False),
        sa.Column("aggregate_id", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("client_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "server_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "client_entry_id", name="uq_outbox_owner_client_entry"
        ),
    )
    op.create_index(
        "ix_outbox_owner_received",
        "outbox_entries",
        ["owner_tenant_id", "owner_user_id", "server_received_at"],
        unique=False,
    )
    op.create_table(
        "summary_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_tenant_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sections_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("user_modified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_summary_templates_updated_at", "summary_templates", ["updated_at"], unique=False
    )
    op.create_table(
        "meeting_notes",
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("notes_markdown", sa.Text(), nullable=True),
        sa.Column("notes_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("meeting_id"),
    )
    op.create_table(
        "summary_processes",
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("processing_time", sa.Float(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("meeting_id"),
    )
    op.create_table(
        "summary_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "version", name="uq_summary_versions_meeting_version"),
    )
    op.create_index(
        "ix_summary_versions_meeting_version",
        "summary_versions",
        ["meeting_id", "version"],
        unique=False,
    )
    op.create_table(
        "transcript_chunks",
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("meeting_name", sa.String(), nullable=True),
        sa.Column("transcript_text", sa.Text(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=True),
        sa.Column("overlap", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("meeting_id"),
    )
    op.create_table(
        "transcript_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("segments_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("segment_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "version", name="uq_transcript_versions_meeting_version"),
    )
    op.create_index(
        "ix_transcript_versions_meeting_version",
        "transcript_versions",
        ["meeting_id", "version"],
        unique=False,
    )
    op.create_table(
        "transcripts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("sequence_number", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("action_items", sa.Text(), nullable=True),
        sa.Column("key_points", sa.Text(), nullable=True),
        sa.Column("audio_start_time", sa.Float(), nullable=True),
        sa.Column("audio_end_time", sa.Float(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("speaker", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transcripts_meeting_id", "transcripts", ["meeting_id"], unique=False)
    op.create_index(
        "ix_transcripts_meeting_sequence",
        "transcripts",
        ["meeting_id", "sequence_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transcripts_meeting_sequence", table_name="transcripts")
    op.drop_index("ix_transcripts_meeting_id", table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_index("ix_transcript_versions_meeting_version", table_name="transcript_versions")
    op.drop_table("transcript_versions")
    op.drop_table("transcript_chunks")
    op.drop_index("ix_summary_versions_meeting_version", table_name="summary_versions")
    op.drop_table("summary_versions")
    op.drop_table("summary_processes")
    op.drop_table("meeting_notes")
    op.drop_index("ix_summary_templates_updated_at", table_name="summary_templates")
    op.drop_table("summary_templates")
    op.drop_index("ix_outbox_owner_received", table_name="outbox_entries")
    op.drop_table("outbox_entries")
    op.drop_index("ix_meetings_owner", table_name="meetings")
    op.drop_table("meetings")
    # ### end Alembic commands ###
